name: Pylint check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install pylint

    - name: Run pylint
      run: pylint workflows
